### ISSUE TITLE
Double icons in the Dock

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app-bundler#19]
When running Octave.app 4.4.0 beta2, when I launch the GUI (by double-clicking Octave-4.4.0.app), two Octave icons appear in the Mac Dock. When I hover over them, the tooltips are different: one is "Octave-4.4.0", and one is "octave-gui".

<img width="60" alt="screen shot 2018-06-23 at 1 58 08 am" src="https://user-images.githubusercontent.com/2618447/41806283-e9c81004-7688-11e8-885a-aa79d42f9e33.png">

**Comment by apjanke** [comment]
I suspect this is because we have one program that's the launcher script, and that appears as "Octave-4.4.0" based on the app bundle name, and it launches another program, `octave`/`octave-gui` from inside the bundle. If I minimize the Octave GUI and then click on the Octave-4.4.0 dock icon, nothing happens. But clicking on "octave-gui" brings it back up.

Maybe this could be fixed with an "exec" inside the launcher script.

**Comment by apjanke** [comment]
[This article](https://discussions.apple.com/thread/323661) says you should be able to do a background shell script by using `&`, but when I tried that, it had no apparent effect, and the double icon remained.

**Comment by schoeps** [comment]
I confirm this. Strangely, I do not recall that this happened on my machine with my original script (maybe macos does something clever internally because it was name Octave.app?).

**Comment by apjanke** [comment]
Darn it!

I will review your original script and one of the old DMGs to see if I am missing something here. This is an unfortunate nit in the build.

**Comment by apjanke** [comment]
I can confirm that the old "Octave_44_Yosemite.dmg" Octave.app posted under http://octave.1599824.n4.nabble.com/Please-test-macOS-dmg-for-4-3-92-td4687817.html does not have the double-icon issue. When I run it, there's just one icon, and it's "octave-gui".

I have no idea what's going on. The launcher script looks the same to me - I just changed it to use a heredoc to generate the file. I will research whether macOS does something clever based on app bundle names.

Maybe it's the fact that I'm pointing `osacompile` at the local `./build/Octave-<whatever>.app` copy in the "munge" step instead of the staged `/Applications/Octave-<whatever>.app`? I'll try pulling it up and doing osacompile into the `/Applications/Octave-<whatever>.app` before copying and munging it.

**Comment by apjanke** [comment]
> Maybe it's the fact that I'm pointing osacompile at the local ./build/Octave-<whatever>.app copy in the "munge" step instead of the staged /Applications/Octave-<whatever>.app?

Nope. I pulled up the `osacompile` step and pointed it at the staged `/Applications/Octave-<whatever>.app`. Still double icon. Maybe it is "Octave.app" naming magic.

**Comment by apjanke** [comment]
Okay, here's a weird thing. [This whole section of `defaults write` calls?](https://github.com/octave-app/octave-app-bundler/blob/50154d57b083cab66bcc1af8f5e1892a0ab0e009/bundle_octave#L482-L490). It seems to be having no effect right now.

When I added some debugging code in locally, the before/after/after-format-conversion states are all the same:

```
Info.plist contents before any writing:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>applet</string>
	<key>CFBundleIconFile</key>
	<string>applet</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Octave-4.4.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>aplt</string>
	<key>LSMinimumSystemVersionByArchitecture</key>
	<dict>
		<key>x86_64</key>
		<string>10.6</string>
	</dict>
	<key>LSRequiresCarbon</key>
	<true/>
</dict>
</plist>
Info.plist contents before conversion:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>applet</string>
	<key>CFBundleIconFile</key>
	<string>applet</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Octave-4.4.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>aplt</string>
	<key>LSMinimumSystemVersionByArchitecture</key>
	<dict>
		<key>x86_64</key>
		<string>10.6</string>
	</dict>
	<key>LSRequiresCarbon</key>
	<true/>
</dict>
</plist>
Info.plist contents:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>applet</string>
	<key>CFBundleIconFile</key>
	<string>applet</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Octave-4.4.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>aplt</string>
	<key>LSMinimumSystemVersionByArchitecture</key>
	<dict>
		<key>x86_64</key>
		<string>10.6</string>
	</dict>
	<key>LSRequiresCarbon</key>
	<true/>
</dict>
</plist>
```

**Comment by schoeps** [comment]
You expect that this is the reason for the two icons?

**Comment by schoeps** [comment]
Did you try to steal the `Info.plist` from my previous build and drop it in the new one?

**Comment by apjanke** [comment]
> Did you try to steal the Info.plist from my previous build and drop it in the new one?

No, `Info.plist` is being regenerated from scratch here. I think it's initially created by [that first `osacompile -o "$install_dir" -e " "` statement](https://github.com/octave-app/octave-app-bundler/blob/50154d57b083cab66bcc1af8f5e1892a0ab0e009/bundle_octave#L234) used when no `Octave-<version>.app` directory exists at at all.

**Comment by apjanke** [comment]
> You expect that this is the reason for the two icons?

I'm just guessing here. This is a bit over my head.

**Comment by apjanke** [comment]
Oh boy. Here's something. The `man defaults` page says this about the "filepath" variant:

```
     filepath  Domains may also be specified as a path to an arbitrary plist
               file, with or without the '.plist' extension. For example:

                     defaults read ~/Library/Containers/com.apple.TextEdit/Data/Library/Preferences/com.apple.TextEdit.plist
[...]

               WARNING: The defaults command will be changed in an upcoming
               major release to only operate on preferences domains. General
               plist manipulation utilities will be folded into a different
               command-line program.
```

I think maybe that warned-about change may have already happened, and the "filepath" variant is no longer supported, and the man page just hasn't been updated yet. Here's what happens when I tested this on a locally-built Octave-4.4.0.app:

```
$ pwd                                                                                                                                           no-double-icon ✱
/Users/janke/local/repos/octave-app-bundler/build/Octave-4.4.0.app/Contents
[~/local/repos/octave-app-bundler/build/Octave-4.4.0.app/Contents]
$ ls Info.plist                                                                                                                                 no-double-icon ✱
Info.plist
[~/local/repos/octave-app-bundler/build/Octave-4.4.0.app/Contents]
$ cat Info.plist                                                                                                                                no-double-icon ✱
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>applet</string>
	<key>CFBundleIconFile</key>
	<string>applet</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Octave-4.4.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>aplt</string>
	<key>LSMinimumSystemVersionByArchitecture</key>
	<dict>
		<key>x86_64</key>
		<string>10.6</string>
	</dict>
	<key>LSRequiresCarbon</key>
	<true/>
</dict>
</plist>
[~/local/repos/octave-app-bundler/build/Octave-4.4.0.app/Contents]
$ defaults write ./Info.plist NSUIElement 1                                                                                                     no-double-icon ✱
[~/local/repos/octave-app-bundler/build/Octave-4.4.0.app/Contents]
$ cat Info.plist                                                                                                                                no-double-icon ✱
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleAllowMixedLocalizations</key>
	<true/>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleExecutable</key>
	<string>applet</string>
	<key>CFBundleIconFile</key>
	<string>applet</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>Octave-4.4.0</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleSignature</key>
	<string>aplt</string>
	<key>LSMinimumSystemVersionByArchitecture</key>
	<dict>
		<key>x86_64</key>
		<string>10.6</string>
	</dict>
	<key>LSRequiresCarbon</key>
	<true/>
</dict>
</plist>
[~/local/repos/octave-app-bundler/build/Octave-4.4.0.app/Contents]
$ defaults read Info.plist                                                                                                                      no-double-icon ✱
{
    NSUIElement = 1;
}
```

To me, that looks like it's completely ignoring the "filepath" option, and treating the argument as a domain identifier: there's no change at all to the `Info.plist` file, but now there's an unrelated defaults domain named `Info.plist`.

Perhaps, if this is what's controlling the icon, your earlier builds worked because you were running the `defaults` command on an earlier version of OS X which still actually supported the "filepath" calling form. This is supported by the fact that you have "Yosemite" in the name of the "Octave_44_Yosemite.DMG" distribution.

I'll try setting up a VM with an earlier version of OS X and see how it works there.

Any chance you still have a copy of your original High Sierra build of 4.3.92 sitting around that you could share for reference?

**Comment by schoeps** [comment]
No, sorry. 4.3.92 is lost (even not anymore in the history of my dropbox). However, I confirm that I did the builds in a Yosemite virtual machine. I thought this makes backward compatibility easier. So your theory is a very plausible explanation. 

What to do? We could create a xml file manually and then convert to plist, right? Most stuff does not change, so we could ship it with the repository....

**Comment by apjanke** [comment]
> What to do? 

For now, I will try building inside a Mavericks VM and see what happens.

For the long term, replace `defaults write` calls with `plistbuddy` calls. It's the new replacement command that knows how to operate on plist files.

**Comment by schoeps** [comment]
Great news, plistbuddy indeed works! This did the trick for me (after making Info.plist writable) 
```
/usr/libexec/PlistBuddy -c "Add :NSUIElement integer 1" /Applications/Octave-4.4.0.app/Contents/Info.plist 
/usr/libexec/PlistBuddy -c "Add :CFBundleIdentifier string org.octave.Octave" /Applications/Octave-4.4.0.app/Contents/Info.plist
/usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string 4.4.0" /Applications/Octave-4.4.0.app/Contents/Info.plist
/usr/bin/plutil -convert xml1 Info.plist
```
The keys `NSHumanReadableCopyright` and `CFBundleVersion` should be analogous but I did not yet figured out to set "CFBundleDocumentTypes".

**Comment by apjanke** [comment]
Excellent! Problem solved.

Here's how the `CFBundleDocumentTypes` turned out: https://github.com/octave-app/octave-app-bundler/blob/5aa2c721f28a5dee908151313ae482b9b05889eb/bundle_octave#L499-L504
