### ISSUE TITLE
Build with FLTK?

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app-bundler#32]
There's currently a crash in the test suite if Octave is built against FLTK and Qt on macOS. https://savannah.gnu.org/bugs/?54169

If we can get this patched up, maybe we can include FLTK, too.

For now, exclude FLTK from the build.

**Comment by apjanke** [comment]
For now, I'm making a separate `octave-fltk` formula that we can use to test the experimental patch from upstream.

https://github.com/octave-app/homebrew-octave-app/commit/24ac086ef632a4ba3aa892bd7d2547dfd85ded98

https://github.com/octave-app/homebrew-octave-app-bases/commit/310d73c84a1cafced9478e01d784f4703c73f1fd

**Comment by schoeps** [comment]
Let us skip fltk. I guess the octave community will discontinue its support anyway soon. These are unpopular decisions and it will be supported as long as possible but ultimately it does not make sense to support 3 backends (gnuplot, fltk and qt).

**Comment by apjanke** [comment]
I hear that.

Proceeding without fltk.
