### ISSUE TITLE
Build broken due to broken libtiff download URLs

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app-bundler#51]
All builds are currently broken because someone removed some of the libtiff patch downloads from their old place on the Debian's server. Sigh.

Homebrew bug for this: https://github.com/Homebrew/homebrew-core/issues/33858

Blocks #39.

Gonna wait for https://github.com/Homebrew/homebrew-core/pull/33918 to host the patches on Homebrew's repo, and then re-grab the libtiff formula to pick that up.

**Comment by claui** [comment]
@apjanke The `libtiff 4.0.9_5` revision is now live. 👍

**Comment by apjanke** [comment]
Thanks @claui!

I've updated to 4.0.9_5 in https://github.com/octave-app/homebrew-octave-app/commit/e30b6e9ba1bcc663ca1c608502bf12afb7d1ea6c and the build is working now.

**Comment by claui** [comment]
@apjanke Just for the record: it was @fxcoudert who did most of the work 👏
