### ISSUE TITLE
sqrt vs ^(1/2)

### ISSUE THREAD

**Issue by ohhmm** [octave-app/octave-app-bundler#55]
implement different functionalities according to words of [El'endia Starman](https://math.stackexchange.com/questions/41784/convert-any-number-to-positive-how/41787#comment5776496_41787)

**Comment by StefanKarpinski** [comment]
I think you can safely close the issue: https://github.com/JuliaLang/julia/issues/30424.

**Comment by ohhmm** [comment]
Principal root returns single result which is correct. But exponentiation to ^(1/2) should return two results.

**Comment by apjanke** [comment]
Ah. That's an issue with Octave itself, not the Octave.app packaging. You can ask about it on the [octave-help mailing list](https://lists.gnu.org/mailman/listinfo/help-octave). I doubt it will be changed, though. This is how square root/fractional exponentiation works in all the programming languages I'm familiar with.

Closing as WONTFIX/upstream.
