### ISSUE TITLE
Qt 5.12 will not build on OS X 10.11

### ISSUE THREAD

**Issue by apjanke** [octave-app/octave-app-bundler#75]
Sheee-it. Looks like Qt 5.12.1 is not compatible with OS X 10.11.

From the `brew install qt` inside `./bundle_octave`:

```
==> Downloading https://download.qt.io/official_releases/qt/5.12/5.12.1/single/qt-everywhere-src-5.12.1.tar.xz
==> Downloading from http://qt.mirror.constant.com/archive/qt/5.12/5.12.1/single/qt-everywhere-src-5.12.1.tar.xz
######################################################################## 100.0%
==> ./configure -verbose -prefix /Applications/Octave-5.1.0.app/Contents/Resources/usr/Cellar/qt/5.12.1 -release -open
==> make
Last 15 lines from /Users/janke/Library/Logs/Homebrew/qt/02.make:
[...]
/private/tmp/qt-20190305-84277-4b8s1r/qt-everywhere-src-5.12.1/qtbase/bin/qfloat16-tables global/qfloat16tables.cpp
/private/tmp/qt-20190305-84277-4b8s1r/qt-everywhere-src-5.12.1/qtbase/bin/rcc -name mimetypes mimetypes/mimetypes.qrc -o .rcc/qrc_mimetypes.cpp
Sorry, "rcc" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.
make[3]: *** [.rcc/qrc_mimetypes.cpp] Error 1
make[3]: *** Waiting for unfinished jobs....
make[2]: *** [sub-corelib-make_first] Error 2
make[1]: *** [sub-src-make_first] Error 2
make: *** [module-qtbase-make_first] Error 2
```

Looks like we'll have to choose between using the older Qt 5.11 (and providing our own versioned formula for that) and increasing Octave.app's minimum supported OS X version to 10.12.

This is complicated by the fact that I can't get an OS X 10.12 VM to install properly on my iMac. Bummer.

**Comment by apjanke** [comment]
@schoeps Need your input on one of this one. It looks like Qt 5.12 no longer supports OS X 10.11 El Capitan; it needs macOS 10.12 Sierra or later. So we can either stick with the old Qt 5.11, or drop support for OS X 10.11 and require macOS 10.12 or later.

What do you think?

How many of your students are still using older OS X versions?

I don't have any formed preferences yet. I figure that most Octave developers and users are running on Linux, which means they're using distro-provided Qts, which are going to be older, so if we stick with an older Qt we're not going to be oddballs.

On the other hand, the Windows Octave install probably builds with the latest Qt, so if we want parity with that, we probably want Qt 5.12.

I do not know of any actual features or bugfixes that would make us prefer Qt 5.12.

I'll ask around the Octave IRC and see what Qts people are running.

**Comment by apjanke** [comment]
Okay, I'll work on setting up a 10.12 build box.

> We will freeze dependencies for version 5, i.e. a year or so, right? 

Actually, I was thinking of re-freezing them with each minor release. I figure that our biggest user base of macOS Octave users (and effectively testers) is Homebrew users installing Octave ([18,000 installs in last 90 days](https://formulae.brew.sh/formula/octave)), and they'll typically be up-to-date with Homebrew core's current versions, so we should keep Octave.app up-to-date to match.

But we could do it either way.

And yeah, the 4.4.1 downloads will stay up. I can add a section directing macOS 10.11 users at them.

**Comment by apjanke** [comment]
Let's just say that our policy from now on will be to support the latest three versions of macOS as of the time of a release. That's all that Homebrew supports, so that's probably all we can really offer, anyway.

**Comment by schoeps** [comment]
Sounds fair to me!

**Comment by apjanke** [comment]
Sigh. I can't even successfully set up a 10.12 build VM right now; I'm getting OS installer signature errors. The early betas for 5.1.0 will be macOS 10.13+ only until I get that sorted out.

**Comment by apjanke** [comment]
Upgrading to 10.12 (10.13 for now) fixed it. Closing.
